
package vistas;

import java.awt.BorderLayout;

/**
 *
 * @author nunez
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        menu = new javax.swing.JPanel();
        btnLanzaderas = new javax.swing.JButton();
        btnNoTripuladas = new javax.swing.JButton();
        btnTripuladas = new javax.swing.JButton();
        titulo = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        fondocosmico = new javax.swing.JLabel();
        content = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menu.setBackground(new java.awt.Color(88, 24, 69));

        btnLanzaderas.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        btnLanzaderas.setForeground(new java.awt.Color(88, 24, 69));
        btnLanzaderas.setText("LANZADERAS");
        btnLanzaderas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLanzaderasMouseClicked(evt);
            }
        });
        btnLanzaderas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLanzaderasActionPerformed(evt);
            }
        });

        btnNoTripuladas.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        btnNoTripuladas.setForeground(new java.awt.Color(88, 24, 69));
        btnNoTripuladas.setText("NO TRIPULADAS");
        btnNoTripuladas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoTripuladasActionPerformed(evt);
            }
        });

        btnTripuladas.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        btnTripuladas.setForeground(new java.awt.Color(88, 24, 69));
        btnTripuladas.setText("TRIPULADAS");
        btnTripuladas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTripuladasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnTripuladas, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNoTripuladas, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLanzaderas, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(btnLanzaderas, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(btnNoTripuladas, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(btnTripuladas, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(156, Short.MAX_VALUE))
        );

        background.add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 600));

        titulo.setBackground(new java.awt.Color(255, 255, 255));
        titulo.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("INVENTARIO DE NAVES ESPACIALES SOFKA");
        background.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 790, 120));

        nombre.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        nombre.setForeground(new java.awt.Color(255, 255, 255));
        nombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombre.setText("JOSE MIGUEL NUÑEZ BERNAL");
        background.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 400, 330, 60));

        fondocosmico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/planetas.png"))); // NOI18N
        background.add(fondocosmico, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 940, 600));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 940, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        background.add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 940, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLanzaderasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLanzaderasMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLanzaderasMouseClicked

    private void btnLanzaderasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLanzaderasActionPerformed
        //se configura el boton lanzadera para que cambie el contenido del jpanel
        lanzaderaPanel lan = new lanzaderaPanel();
        lan.setSize(940, 600);
        lan.setLocation(0, 0);
        
        content.removeAll();
        content.add(lan, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_btnLanzaderasActionPerformed

    private void btnNoTripuladasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoTripuladasActionPerformed
        
        noTripuladaPanel noTri = new noTripuladaPanel();
        noTri.setSize(940, 600);
        noTri.setLocation(0, 0);
        
        content.removeAll();
        content.add(noTri, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_btnNoTripuladasActionPerformed

    private void btnTripuladasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTripuladasActionPerformed
        
        tripuladaPanel Tri = new tripuladaPanel();
        Tri.setSize(940, 600);
        Tri.setLocation(0, 0);
        
        content.removeAll();
        content.add(Tri, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_btnTripuladasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton btnLanzaderas;
    private javax.swing.JButton btnNoTripuladas;
    private javax.swing.JButton btnTripuladas;
    private javax.swing.JPanel content;
    private javax.swing.JLabel fondocosmico;
    private javax.swing.JPanel menu;
    private javax.swing.JLabel nombre;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
